// user
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// cart
export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";

export const ADD_PRODUCT_INTO_CART_REQUEST = "ADD_PRODUCT_INTO_CART_REQUEST";
export const ADD_PRODUCT_INTO_CART_SUCCESS = "ADD_PRODUCT_INTO_CART_SUCCESS";
export const ADD_PRODUCT_INTO_CART_ERROR = "ADD_PRODUCT_INTO_CART_ERROR";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

export const FETCH_PRODUCTBYID_REQUEST = "FETCH_PRODUCTBYID_REQUEST";
export const FETCH_PRODUCTBYID_SUCCESS = "FETCH_PRODUCTBYID_SUCCESS";
export const FETCH_PRODUCTBYID_ERROR = "FETCH_PRODUCTBYID_ERROR";
