// user
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "FETCH_USER_ERROR";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

// cart
export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";

export const ADD_PRODUCT_INTO_CART_REQUEST = "ADD_PRODUCT_INTO_CART_REQUEST";
export const ADD_PRODUCT_INTO_CART_SUCCESS = "ADD_PRODUCT_INTO_CART_SUCCESS";
export const ADD_PRODUCT_INTO_CART_ERROR = "ADD_PRODUCT_INTO_CART_ERROR";

export const DELETE_PRODUCTINCART_REQUEST = "DELETE_PRODUCTINCART_REQUEST";
export const DELETE_PRODUCTINCART_SUCCESS = "DELETE_PRODUCTINCART_SUCCESS";
export const DELETE_PRODUCTINCART_ERROR = "DELETE_PRODUCTINCART_ERROR";
// product
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_ERROR = "SEARCH_PRODUCT_ERROR";

// category
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";

export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const FETCH_CATEGORYBYID_REQUEST = "FETCH_CATEGORYBYID_REQUEST";
export const FETCH_CATEGORYBYID_SUCCESS = "FETCH_CATEGORYBYID_SUCCESS";
export const FETCH_CATEGORYBYID_ERROR = "FETCH_CATEGORYBYID_ERROR";

export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";

export const FETCH_PRODUCTBYID_REQUEST = "FETCH_PRODUCTBYID_REQUEST";
export const FETCH_PRODUCTBYID_SUCCESS = "FETCH_PRODUCTBYID_SUCCESS";
export const FETCH_PRODUCTBYID_ERROR = "FETCH_PRODUCTBYID_ERROR";

// author
export const FETCH_AUTHOR_REQUEST = "FETCH_AUTHOR_REQUEST";
export const FETCH_AUTHOR_SUCCESS = "FETCH_AUTHOR_SUCCESS";
export const FETCH_AUTHOR_ERROR = "FETCH_AUTHOR_ERROR";

export const CREATE_AUTHOR_REQUEST = "CREATE_AUTHOR_REQUEST";
export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
export const CREATE_AUTHOR_ERROR = "CREATE_AUTHOR_ERROR";

export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";

export const FETCH_AUTHORBYID_REQUEST = "FETCH_AUTHORBYID_REQUEST";
export const FETCH_AUTHORBYID_SUCCESS = "FETCH_AUTHORBYID_SUCCESS";
export const FETCH_AUTHORBYID_ERROR = "FETCH_AUTHORBYID_ERROR";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";

//bill
export const FETCH_BILL_REQUEST = "FETCH_BILL_REQUEST";
export const FETCH_BILL_SUCCESS = "FETCH_BILL_SUCCESS";
export const FETCH_BILL_ERROR = "FETCH_BILL_ERROR";

//order
export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";

// move product into payload
export const MOVE_PRODUCTINTOPAYLOAD_SUCCESS =
  "MOVE_PRODUCTINTOPAYLOAD_SUCCESS";
